### ISSUE TITLE
ImportError: No module named 'pandas.compat.numpy_compat' when running tests

### ISSUE THREAD

**Issue by zrisher** [open-source-economics/Tax-Calculator#661]
Following the [getting started guide](http://taxcalc.readthedocs.org/en/latest/contributor_guide.html), upon running `py.test -m "not requires_pufcsv"` a user is presented with 13 errors, all:

```
...\Miniconda3\envs\taxcalc-dev\lib\site_packages\pandas\__init.py:22: in (module)
     from pandas.compat.numpy_compat import *
E   ImportError: No module named 'pandas.compat.numpy_compat'
```

`pandas.compat.numpy_compat.py` was added to pandas in January 2016, whereas the version of pandas specified in `environment.yml` was released in June 2015. Why/how a pandas release from 2015 is requiring code that wasn't added until 2016, I have no idea. Hopefully someone can improve my understanding of the package distribution on this point.

However, if I remove the version constraint in environment.yml, pandas 0.18.0 installs successfully and all the tests pass (besides the unrelated one mentioned in #660). Is there current reason for the `<=0.16.2` constraint?

**Comment by talumbau** [comment]
We ended up pinning `taxcalc` to pandas versions because one time last year we deployed and automatically got the new version of pandas, which was not backwards compatible, so we had strange errors. So, "once bit, twice shy." Now we only move forward with new pandas versions when someone takes the time to make sure that `taxcalc` and `dropq` work properly with the new version. It sounds like we might be good to go to upgrade to version 0.18. I don't understand how you could have gotten the error message you got, but if you are using a conda environment with pandas 0.16.2, I don't see how you could be interacting with version 0.18 of pandas.

**Comment by zrisher** [comment]
@talumbau Totally makes sense. I still don't quite understand why that error appears either, but upgrading `pandas` to `0.18.0` indeed fixes it, and the tests run fine. I have a sneaking suspicion it has something to do with the `numpy` version, because the files being included into `pandas` seemed to be introduced due to changes in `numpy`, and its current version requires `pandas 0.18.0`. 

So I'm putting together a PR that locks both `pandas` and `numpy` at their currently working versions. In Ruby this is commonly done by locking the major version (and allowing updated minor versions), since we normally expect compatability changes only with major versions for projects that follow semantic versioning. The syntax for that in Ruby is `~> 0.18.0` (which would mean 0.18.0 -> 0.18.9). Does a similar constraint exist with Conda? I can't find documentation on it. If so, I'll update my PR to use it.

**Comment by zrisher** [comment]
I narrowed this down to an issue with Conda. In the `pandas` package it installed:

`pandas                    0.16.2               np19py35_0    http://repo.continuum.io/pkgs/free/win-64/pandas-0.16.2-np19py35_0.tar.bz2`

the `__init__.py` file is more recent that the one supplied for release 0.16.2 on the `pandas` github repo, so it references files that don't exist in the rest of the package.

Changing the pandas version or python version fixes this issue. So #669 is still a good solution, as long as someone can get it to pass the puf.csv tests.

**Comment by talumbau** [comment]
Thanks for finding this @zrisher can you file this issue on the conda issue tracker?

**Comment by zrisher** [comment]
@talumbau Done in https://github.com/conda/conda/issues/2328!

For some reason I thought there would be individual package pages where I'd need to raise the issue, like Pip has. It's very nice to see the condas repo takes responsibility for all packages installed through it.

Please still merge #669 when you have time to give it a try - it fixes this error for me and is useful in that it updates pandas and numpy, and locks them together.

**Comment by martinholmer** [comment]
Zach (@zrisher),
Would you say that issue #661 would be resolved if I merged your pull request #669?

T.J. gave his approval to pull request #669.

Does anybody have any problems or concerns about pull request #669?
If none are raised, I'll merge #669 and and close issue #661 on Wednesday, April 27th.

@MattHJensen @talumbau

**Comment by zrisher** [comment]
@martinholmer Yes, this is fixed by #669 and I'm good on merging it. Thank you!
